# Generated by Django 5.2.17 on 2026-09-08 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm_id', models.CharField(max_length=32, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dist_to_mule_branch_km', models.FloatField(default=0.5)),
                ('past_fraud_cases', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CyberComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank=True, max_length=64, unique=True)),
                ('crime_type', models.CharField(choices=[('UPI Fraud', 'UPI Fraud'), ('Card Fraud', 'Card Fraud'), ('Phishing', 'Phishing'), ('Investment Scam', 'Investment Scam'), ('Job Scam', 'Job Scam')], default='UPI Fraud', max_length=50)),
                ('amount_lost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reporting_lag_mins', models.IntegerField(default=20, help_text='Minutes between fraud and complaint filing')),
                ('mule_hops', models.IntegerField(default=2, help_text='Number of accounts traversed')),
                ('incident_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_holder', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('layer', models.IntegerField(default=3, help_text='Mule Layer (e.g. 1, 2, 3)')),
                ('at_risk_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_score', models.IntegerField(default=85)),
                ('is_lien_placed', models.BooleanField(default=False)),
                ('target_atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mule_accounts', to='core.atmlocation')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField(help_text='Predicted probability percentage 0-100')),
                ('predicted_time_window', models.CharField(default='18:00 - 21:00', max_length=50)),
                ('status', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=20)),
                ('recommended_action', models.TextField()),
                ('factor_previous_cases', models.IntegerField(default=90)),
                ('factor_pattern_match', models.IntegerField(default=85)),
                ('factor_time_risk', models.IntegerField(default=75)),
                ('factor_proximity', models.IntegerField(default=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.atmlocation')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cybercomplaint')),
            ],
        ),
    ]
