# Generated by Django 5.2.17 on 2026-09-09 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cybercomplaint',
            name='mule_hops',
            field=models.IntegerField(default=2, help_text='Number of intermediary accounts traversed'),
        ),
        migrations.AlterField(
            model_name='muleaccount',
            name='layer',
            field=models.IntegerField(default=1, help_text='Mule Layer (e.g. 1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='predictionhotspot',
            name='atm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictionhotspot', to='core.atmlocation'),
        ),
        migrations.AlterField(
            model_name='predictionhotspot',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictionhotspot', to='core.cybercomplaint'),
        ),
        migrations.AlterField(
            model_name='predictionhotspot',
            name='factor_pattern_match',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='predictionhotspot',
            name='factor_previous_cases',
            field=models.IntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='predictionhotspot',
            name='factor_proximity',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='predictionhotspot',
            name='predicted_time_window',
            field=models.CharField(default='18:00 - 21:00', max_length=80),
        ),
        migrations.AlterField(
            model_name='predictionhotspot',
            name='risk_score',
            field=models.IntegerField(help_text='Predicted cashout probability percentage (0-100)'),
        ),
    ]
