# Generated by Django 5.2.17 on 2026-09-10 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cybercomplaint_mule_hops_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncrp_id', models.CharField(max_length=50, unique=True)),
                ('citizen_phone', models.CharField(max_length=15)),
                ('amount_lost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reporting_lag', models.IntegerField()),
                ('mule_hops', models.IntegerField()),
                ('threat_score', models.IntegerField()),
                ('status', models.CharField(choices=[('LOGGED', 'Complaint Logged'), ('FROZEN', 'Lien Placed / Frozen'), ('REFUND_PENDING', 'Pending Court/Bank Clearance'), ('REFUNDED', 'Money Credited to Victim')], default='LOGGED', max_length=30)),
                ('refund_reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('I4C_ADMIN', 'I4C Admin'), ('LEA_OFFICER', 'LEA Police Officer'), ('BANK_NODAL', 'Bank Nodal Officer')], max_length=20)),
                ('organization', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='muleaccount',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mule_accounts', to='core.cybercomplaint'),
        ),
        migrations.AddField(
            model_name='muleaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='muleaccount',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='muleaccount',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muleaccount',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Lien Placed', 'Lien Placed (Frozen)'), ('REFUNDED', 'Refunded to Citizen')], default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='predictionhotspot',
            name='atm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictionhotspots', to='core.atmlocation'),
        ),
        migrations.AlterField(
            model_name='predictionhotspot',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictionhotspots', to='core.cybercomplaint'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS Gateway'), ('EMAIL', 'Email Alert'), ('API_WEBHOOK', 'LEA / Bank Webhook'), ('DASHBOARD', 'Dashboard Trigger')], max_length=20)),
                ('recipient_agency', models.CharField(choices=[('LEA_POLICE', 'Law Enforcement Agency'), ('BANK_NODAL', 'Bank FRM Desk'), ('I4C_ADMIN', 'I4C Command Matrix')], max_length=30)),
                ('recipient_contact', models.CharField(default='All Registered Units', max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('SENT', 'Sent'), ('TRIGGERED', 'Triggered'), ('FAILED', 'Failed')], default='DELIVERED', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cybercomplaint')),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.predictionhotspot')),
            ],
        ),
    ]
