# Generated by Django 5.2.17 on 2026-09-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_incident_officialuser_muleaccount_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercomplaint',
            name='suspect_utr',
            field=models.CharField(blank=True, default='UTR-2026-98124', help_text='Transaction Reference or UPI UTR Number', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='suspect_utr',
            field=models.CharField(blank=True, default='UTR-2026-98124', max_length=100),
        ),
        migrations.AddField(
            model_name='muleaccount',
            name='utr_ref',
            field=models.CharField(blank=True, default='UTR-2026-98124', help_text='CFCFRMS Downstream UTR Trace', max_length=100),
        ),
    ]
