# Generated by Django 5.2.17 on 2026-09-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cybercomplaint_suspect_utr_incident_suspect_utr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercomplaint',
            name='victim_account_masked',
            field=models.CharField(blank=True, default='XXXX-XXXX-9842', help_text='Debited Account Number (Masked)', max_length=50),
        ),
        migrations.AddField(
            model_name='cybercomplaint',
            name='victim_bank',
            field=models.CharField(blank=True, default='State Bank of India', help_text='Originating Bank Name', max_length=100),
        ),
        migrations.AddField(
            model_name='cybercomplaint',
            name='victim_ifsc',
            field=models.CharField(blank=True, default='SBIN0040281', help_text='Originating Bank Branch IFSC', max_length=20),
        ),
        migrations.AddField(
            model_name='cybercomplaint',
            name='victim_name',
            field=models.CharField(blank=True, default='Ananya Sharma (Victim)', help_text='Complainant / Account Holder Name', max_length=120),
        ),
        migrations.AddField(
            model_name='incident',
            name='victim_account_masked',
            field=models.CharField(blank=True, default='XXXX-XXXX-9842', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='victim_bank',
            field=models.CharField(blank=True, default='State Bank of India', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='victim_ifsc',
            field=models.CharField(blank=True, default='SBIN0040281', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='victim_name',
            field=models.CharField(blank=True, default='Ananya Sharma (Victim)', max_length=120),
        ),
    ]
